# Create a program that read any integer number and displays its multiplication table on the screen:

number = int(input('Enter the number: '))
print('=' * 20)
print('The multiplication table of {} is:'.format(number))
print('{} x {:2} = {:2}'.format(number, 0, number * 0))
print('{} x {:2} = {:2}'.format(number, 1, number* 1))
print('{} x {:2} = {:2}'.format(number, 2, number * 2))
print('{} x {:2} = {:2}'.format(number, 3, number * 3))
print('{} x {:2} = {:2}'.format(number, 4, number * 4))
print('{} x {:2} = {:2}'.format(number, 5, number * 5))
print('{} x {:2} = {:2}'.format(number, 6, number * 6))
print('{} x {:2} = {:2}'.format(number, 7, number * 7))
print('{} x {:2} = {:2}'.format(number, 8, number * 8))
print('{} x {:2} = {:2}'.format(number, 9, number * 9))
print('{} x {:2} = {:2}'.format(number, 10, number * 10))
print('=' * 20)